// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbBpbx7rgByl-IHcvro4CqPr5v0_IlwCk',
    appId: '1:458447257200:android:d58daabc37b7ec06303eb5',
    messagingSenderId: '458447257200',
    projectId: 'taskflow-plus',
    storageBucket: 'taskflow-plus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQEOyjsknk1upgLx3grOA5BBDTjiAD-qs',
    appId: '1:458447257200:ios:87a73c8227e5f79c303eb5',
    messagingSenderId: '458447257200',
    projectId: 'taskflow-plus',
    storageBucket: 'taskflow-plus.firebasestorage.app',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDDlheaSRjYJj9QUH8znxA-6DPg69lpCc',
    appId: '1:458447257200:web:b7cb8cba3d98e103303eb5',
    messagingSenderId: '458447257200',
    projectId: 'taskflow-plus',
    authDomain: 'taskflow-plus.firebaseapp.com',
    storageBucket: 'taskflow-plus.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQEOyjsknk1upgLx3grOA5BBDTjiAD-qs',
    appId: '1:458447257200:ios:87a73c8227e5f79c303eb5',
    messagingSenderId: '458447257200',
    projectId: 'taskflow-plus',
    storageBucket: 'taskflow-plus.firebasestorage.app',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDDlheaSRjYJj9QUH8znxA-6DPg69lpCc',
    appId: '1:458447257200:web:ac65a72b4a729e88303eb5',
    messagingSenderId: '458447257200',
    projectId: 'taskflow-plus',
    authDomain: 'taskflow-plus.firebaseapp.com',
    storageBucket: 'taskflow-plus.firebasestorage.app',
  );

}